name: NUKE fuk all !!!
on:
  workflow_dispatch
jobs:   
  destroy-terraform:
    if: github.actor == 'trucdp'
    runs-on: ubuntu-latest
    environment: dev
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ vars.AWS_REGION }}
    steps:   
     - name: Checkout repository
       uses: actions/checkout@v4
     - name: Invoke Terraform Command
       shell: bash
       run: |
        cd terraform
        terraform init
        terraform destroy -auto-approve
